### PR TITLE
fixes #41 do not throw an error during building if modules is defined…

### LINKED ISSUE #41: An mistake in the wrap method?
I think, instead of 
```js
'(function(g) {\n' +
         '  var __bem_xjst = function(exports' + modulesProvidedDeps + ') {\n' +
         '     ' + code + ';\n' +
         '     return exports;\n' +
         '  }\n' +
         '  var defineAsGlobal = true;\n' +
         '  if(typeof exports === "object") {\n' +
         '    exports["' + exportName + '"] = __bem_xjst({}' + modulesProvidedDeps + ');\n' +
         '    defineAsGlobal = false;\n' +
         '  }\n' +
         '  if(typeof modules === "object") {\n' +
         '    modules.define("' + exportName + '"' + modulesDeps + ',\n' +
         '      function(provide' + modulesProvidedDeps + ') {\n' +
         '        provide(__bem_xjst({}' + modulesProvidedDeps + ')) });\n' +
         '    defineAsGlobal = false;\n' +
         '  }\n' +
         '  defineAsGlobal && (g["' + exportName + '"] = __bem_xjst({}' + modulesProvidedDeps + '));\n' +
         '})(this);'
```

we should use

```js
'(function(g) {\n' +
         '  var __bem_xjst = function(exports' + modulesProvidedDeps + ') {\n' +
         '     ' + code + ';\n' +
         '     return exports;\n' +
         '  }\n' +
         '  var defineAsGlobal = true;\n' +
         '  if(typeof modules === "object") {\n' +
         '    modules.define("' + exportName + '"' + modulesDeps + ',\n' +
         '      function(provide' + modulesProvidedDeps + ') {\n' +
         '        provide(__bem_xjst({}' + modulesProvidedDeps + ')) });\n' +
         '    defineAsGlobal = false;\n' +
         '  }\n' +
         '  else if(typeof exports === "object") {\n' +
         '    exports["' + exportName + '"] = __bem_xjst({}' + modulesProvidedDeps + ');\n' +
         '    defineAsGlobal = false;\n' +
         '  }\n' +
         '  defineAsGlobal && (g["' + exportName + '"] = __bem_xjst({}' + modulesProvidedDeps + '));\n' +
         '})(this);'
```

because now we force users of bemhtml/bemtree to use global variables in node.js context.

### PR DESCRIPTION
**Pull request by jifeon**
#61 for v1.x

It would be great to see it as hot fix in 1.x version before you release v2.0

### CODE REVIEW

**Comment by tadatuta** [comment]
JFYI, there's already `4.0.1` and we have `1.x` and `4.x` branches in support currently

**Comment by tadatuta** [comment]
looks like we don't need it anymore after https://github.com/enb-bem/enb-bemxjst/pull/83/files ?

**Comment by apsavin** [comment]
Can I check it with the latest bem-core?

**Comment by tadatuta** [comment]
@apsavin yes, latest commit to `bem-core` has the version with this change of `enb-bemxjst`

**Comment by apsavin** [comment]
Yes, looks like we don't need it anymore.

**Pull request closed without merging**
