### PR TITLE
tree: verify `.match()` arguments

### PR DESCRIPTION
**Pull request by indutny**
Fix: #106 

cc @tadatuta

### CODE REVIEW

**Comment by indutny** [comment]
@arikon there is no row for this in our wiki, the estimated time spent on this is 1/2 hour.

**Comment by tadatuta** [comment]
LGTM

**Comment by indutny** [comment]
Landed and released, thank you!

**Comment by arikon** [comment]
@indutny Thanks, added! Feel free to add yourself next time ;)

**Pull request closed without merging**
