### PR TITLE
Update default demo example (fix for #368)

### PR DESCRIPTION
**Pull request by miripiruni**
Current example is awful. I try to change it with new possibilities:
— template body parameters instead of `this` and `this.ctx`
— arrow functions
— show `add*()` mode example
— show `match()` power
— add some comments about what it is

DEMO: https://goo.gl/6TbK7a

@tadatuta @zxqfox what you say?

### CODE REVIEW

**Comment by miripiruni** [comment]
The only question is: may we use arrow functions in demo? Is it understandably?

**Comment by zxqfox** [comment]
Need to decide what to do with naming: `(context, json)`.
Anything else lgtm.

**Comment by miripiruni** [comment]
@zxqfox what about arrow functions? Is it acceptable?

**Comment by miripiruni** [comment]
@zxqfox about naming: since user can choose any names I want to offer not dwell on this.

**Comment by tadatuta** [comment]
we use `(node, ctx)` on own projects

**Comment by miripiruni** [comment]
@tadatuta why first argument is `node`? It’s `this` — context of template. Why second argument is `ctx` (so ambiguous)? It’s current BEMJSON nodeю

**Comment by zxqfox** [comment]
@miripiruni because ctx is var ctx = this.ctx;

**Comment by miripiruni** [comment]
@zxqfox name `ctx` without context of using is so blurry. While `json` is more accurately. Do you think so?

**Comment by tadatuta** [comment]
I don't like `json` at all. `json` is javascript object notation. It's like calling a variable `integer` or `array`.

`node` is actually `bem-xjst` node as a kind of instance with all the data, helpers and its children. And `ctx` is just current BEMJSON context will set of fields to read from.

**Comment by miripiruni** [comment]
@tadatuta 

> I don't like json at all. json is javascript object notation. It's like calling a variable integer or array.

Do not confuse the type and name. Type `JSON` but name `json`. Type `Array` but name `array`.

> node is actually bem-xjst node as a kind of instance with all the data, helpers and its children. And ctx is just current BEMJSON context will set of fields to read from.

There is no instance of data. It’s one context that was created once at start. That’s why I don’t understand your variant `node`.

**Comment by tadatuta** [comment]
> Do not confuse the type and name. Type `JSON` but name `json`. Type `Array` but name `array`.

I don't confuse them, I just don't like such names ;)

> There is no instance of data. It’s one context that was created once at start. That’s why I don’t understand your variant node.

That's not quite so:
1. `this.block`, `this.elem`, `this.mods` are always about current node.
2. With `applyNext({ blah: 42 })` you'll be able to get `this.blah` only inside subtree of the current node.
3. There are not just contextual data but some helper functions in `this` as well.

And that's why I like `node` ;)

**Pull request merged**
