### PR TITLE
BEMHTML: support nested mixes

### LINKED ISSUE #241: Support nested mixes
`jsParams` and CSS classes should be merged from all mixes templates.

See https://github.com/bem/bem-core/issues/806 and https://github.com/bem/bem-core/issues/807 for details

### PR DESCRIPTION
**Pull request by miripiruni**
Fix #241 

Instead of https://github.com/bem/bem-xjst/pull/280

### CODE REVIEW

**Comment by miripiruni** [comment]
screen shot 2017-05-10 at 17 27 54

```
$ rm -fr ./dat-5aad5-a2d25 && node runner.js --rev1 5aad540b0d97e379372558e688ab9021d44eea9b --rev2 a2d25efb5a93bbf28c8b386dbb9f95c8dc3bc2ca --bemjson 10000 --dataPath ~/bemjson --templatePath ./template-8x.js
Test started…
{ _: [],
  h: false,
  help: false,
  rev1: '5aad540b0d97e379372558e688ab9021d44eea9b',
  rev2: 'a2d25efb5a93bbf28c8b386dbb9f95c8dc3bc2ca',
  bemjson: 10000,
  dataPath: '/Users/miripiruni/bemjson',
  templatePath: './template-8x.js',
  '$0': 'runner.js',
  repeat: undefined,
  verbose: undefined }
Wed May 10 2017 17:19:30 GMT+0300 (MSK)
Total test time:  238615.161181
./lib/compare.py ./dat-5aad5-a2d25 ./dat-5aad5-a2d25/5aad540b0d97e379372558e688ab9021d44eea9b-10000-1494426090791.dat ./dat-5aad5-a2d25/a2d25efb5a93bbf28c8b386dbb9f95c8dc3bc2ca-10000-1494426208718.dat


Percentile:  0.5
{ rev1: 7.719904,
  rev2: 7.520985,
  'diff abs': 0.19891900000000007,
  'diff percent': 2.576703026358873 }

Percentile:  0.9
{ rev1: 10.773798,
  rev2: 10.624067,
  'diff abs': 0.14973099999999917,
  'diff percent': 1.3897698843063466 }

Percentile:  0.95
{ rev1: 12.338903,
  rev2: 12.196022,
  'diff abs': 0.14288100000000092,
  'diff percent': 1.1579716608518642 }

```

**Comment by miripiruni** [comment]
@veged @qfox what do you think:

~1% tradeoff (95 percentile) on benchmark — is it OK?

**Comment by qfox** [comment]
@miripiruni I think any perf trade should be worth the feature being implemented. It's hard to tell whether that is the case here. Furthermore this PR introduces 11k loc and there's no way in hell anybody is going to be able to review this properly, so good luck with that.

I would give more insights but aside from this PR not really being reviewable, I simply don't know enough about this project to begin with even it it was. Perhaps @zxqfox does, though.

**Comment by qfox** [comment]
PS. It's impressive that the 11k loc and one test actually improved code coverage by 0.001%. It's in fact so impressive that would suggest somebody take a closer look at that because it's pretty unlikely to be correct.

**Comment by miripiruni** [comment]
@qfox my apologies, I think it’s second time when I confused nickname. That’s because @zxqfox have ‘qfox’ username as corporate login…

You can ban me :)

**Comment by qfox** [comment]
> You can ban me :)

*shrug* that's okay :)

> P..S. 11K loc in bench dir. But coverage watch only lib dir.

Ah that makes sense.

**Comment by qfox** [comment]
@zxqfox ^

**Comment by miripiruni** [comment]
bem-xjst@8.7.1

**Pull request merged**
