### PR TITLE
compiler: forward-port ContextReplacer from bem-bl

### PR DESCRIPTION
**Pull request by indutny**
Fix: #63

cc @arikon PTAL

### CODE REVIEW

**Comment by indutny** [comment]
cc @vkz

**Comment by arikon** [comment]
@indutny In some test there is an error: Maximum call stack size exceeded

**Comment by indutny** [comment]
I think this was landed. @arikon do you have a test case to reproduce the problem?

**Comment by arikon** [comment]
@indutny All the tests are passing now. Templates were rewritten and merged.

**Comment by indutny** [comment]
Cool!

**Pull request closed without merging**
