### PR TITLE
wrong name of variable

### PR DESCRIPTION
**Pull request by maksugr**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by miripiruni** [comment]
@maksugr can you change the same in english documentation?

**Comment by maksugr** [comment]
@miripiruni done - https://github.com/bem/bem-xjst/pull/318 - sorry for two PR's

**Comment by miripiruni** [comment]
@maksugr why do you use bem:docs-anchors as target branch instead of master?

**Comment by maksugr** [comment]
@miripiruni I think it is default behavior of prose.io (I used it to generate pull request). When you click 'Changes to Submit' in prose.io it doesn't allow control anything.

**Comment by miripiruni** [comment]
@vithar @tadatuta why prose.io PR commit in `bem:docs-anchors` branch instead of master?

**Comment by miripiruni** [comment]
@vithar @tadatuta more over, I want remove `docs-anchors` branch. What happens in this case?

**Comment by miripiruni** [comment]
@maksugr thank you!

**Comment by vithar** [comment]
You can remove this branch freely.

**Pull request merged**
