### PR TITLE
runtime: adapt to the faster dev mode in xjst

### PR DESCRIPTION
**Pull request by indutny**
xjst is now reversing the statements in a dev mode, adapt to these
changes and make sure to run the templates in a correct order.

See: https://github.com/veged/xjst/pull/43

### CODE REVIEW

**Comment by indutny** [comment]
NOTE: depends on https://github.com/veged/xjst/pull/43, do not land before https://github.com/veged/xjst/pull/43 will be released in a next minor version.

**Comment by indutny** [comment]
I think there is a nasty bug, please do not merge yet...

**Comment by indutny** [comment]
Nah, nvm.

**Comment by apsavin** [comment]
@indutny what's with this feature? 
"faster dev mode" sounds very sweet.

**Comment by indutny** [comment]
It is not relevant anymore! Sorry.

**Pull request closed without merging**
