### PR TITLE
bemxjst: should not inherit `mods` from namesake parent block

### PR DESCRIPTION
**Pull request by incrop**
https://nda.ya.ru/3RZ4pf
/cc @miripiruni

### CODE REVIEW

**Comment by a-x-** [comment]
@incrop ссылка внутренняя

**Comment by a-x-** [comment]
tmp

**Comment by miripiruni** [comment]
LGTM

**Comment by miripiruni** [comment]
Also, it fixed #269 

@incrop can you add test for it?

**Comment by incrop** [comment]
@miripiruni sure. Check it out.

**Comment by miripiruni** [comment]
@incrop move replace test to test/modes-replace-test.js please.

**Comment by miripiruni** [comment]
LGTM! Thank you!

**Comment by zxqfox** [comment]
LGTM!

**Pull request merged**
