### PR TITLE
bemhtml: fix elemMods behaviour

### PR DESCRIPTION
**Pull request by miripiruni**
Fixes: #111

P.S. Absolutely identical with https://github.com/bem/bem-xjst/pull/150

### CODE REVIEW

**Comment by zxqfox** [comment]
:+1:

**Comment by miripiruni** [comment]
Just remove unnecessary line https://github.com/bem/bem-xjst/pull/150/files#diff-babcc1050af43cb83540193c8c57664dR407

**Comment by miripiruni** [comment]
JFYI The fix depends on 85e02cc and I cannot release it in 4.4.0. Will be released in 5.0.0

**Pull request merged**
