### PR TITLE
BEMHTML: #204 Templates should be able to override tag from BEMJSON

### PR DESCRIPTION
**Pull request by miripiruni**
Immediate fix for https://github.com/bem/bem-xjst/issues/204

//cc @veged @tadatuta

### CODE REVIEW

**Comment by tadatuta** [comment]
lgtm

**Comment by miripiruni** [comment]
cc @tavriaforever

**Comment by tavriaforever** [comment]
Спасибуленьки!

**Comment by miripiruni** [comment]
BTW, I checked priority of mode vs bemjson field: https://gist.github.com/miripiruni/7561cc8ad56d0d4d5184   (russian).

**Comment by veged** [comment]
LGTM :+1:

**Comment by zxqfox** [comment]
:+1: 

@miripiruni Guess we should check all mods to follow this convention (template first).

**Pull request merged**
