### PR TITLE
BEMHTML: fix render i-bem when mix elem with js (fix #441)

### LINKED ISSUE #441: Add `i-bem` class when mixed element has `js: true` with `elemJsInstances: true`
### Input code or something about issue background

```js
{
    block: 'b',
    content: {
        elem: 'e1',
        mix: { elem: 'e2', js: true }
    }
}
```

### Expected Behavior

```html
<div class="b"><div class="b__e1 b__e2 i-bem" data-bem='{"b__e2":{}}'></div></div>
```

### Actual Behavior

```html
<div class="b"><div class="b__e1 b__e2" data-bem='{"b__e2":{}}'></div></div>
```
(no `i-bem` class).

bem-xjst version and all relevant details
`bem-xjst 7.x / 8.x`, with `elemJsInstances: true`

### PR DESCRIPTION
**Pull request by miripiruni**
Fixes #441

### CODE REVIEW

**Comment by miripiruni** [comment]
@tadatuta @zxqfox is there valide case where we want mix mods/elemMods with js?

```js
// mods
{
    block: 'b',
    mix: { mods: {test: 'ok', js: true } }
}

// elemMods

{
    block: 'b',
    elem: 'e',
    mix: { elemMods: {test: 'ok', js: true } }
}
```

hm?

**Comment by tadatuta** [comment]
@miripiruni 
the example you provided is not about mods mixed with js params, it means just boolean js modifier: `_js`.

as for
```js
{
    block: 'b',
    mix: { mods: { test: 'ok' }, js: true }
}
```
it should be valid but quite strange case (there's no reason not to use `js` outside of the mix).

**Comment by miripiruni** [comment]
@tadatuta so, we cover all cases and I can merge it?

**Comment by tadatuta** [comment]
yes, I think so

**Pull request merged**
