### PR TITLE
runtime: escaping optimization

### PR DESCRIPTION
**Pull request by mishanga**

### CODE REVIEW

**Comment by sbmaxx** [comment]
@mishanga :)) https://github.com/sbmaxx/bem-xjst/commit/3ef0556212a4ff4c916d89bf7dbe943ca072cdce Опередил!

**Comment by mishanga** [comment]
@sbmaxx да я и не особо торопился ;)

**Comment by indutny** [comment]
Супер! Спасибо

**Comment by indutny** [comment]
Benchmark results:

```
$ node bench/run.js --compare --min-samples 900
render:basic:next x 947,236 ops/sec ±0.25% (938 runs sampled)
render:basic:prev x 946,538 ops/sec ±0.29% (938 runs sampled)
render:islands:next x 1,401 ops/sec ±0.35% (936 runs sampled)
render:islands:prev x 1,307 ops/sec ±0.31% (937 runs sampled)
render:showcase:next x 2,547 ops/sec ±0.33% (937 runs sampled)
render:showcase:prev x 2,455 ops/sec ±0.30% (937 runs sampled)
```

**Comment by indutny** [comment]
It looks like it gives 3-7% improvement on `islands` and `showcase`. LGTM

**Comment by indutny** [comment]
Landed and released in 4.2.4. Thank you!

**Comment by mishanga** [comment]
:+1:

**Pull request closed without merging**
