### PR TITLE
Runtime lint: check mix the same mods

### PR DESCRIPTION
**Pull request by miripiruni**
Fix for #350 
Fix for #351

TODO
 - [x] Check mods
 - [x] Check elemMods
 - [x] Check naming

cc @a-x-

### CODE REVIEW

**Comment by miripiruni** [comment]
Runtime warnings:

```bash
BEM-XJST WARNING: you’re trying to mix block with mods to the same block with the same mods.
ctx: {"block":"mix-mod","mods":{"m":1},"mix":[{"mods":{"m":2}}]}

BEM-XJST WARNING: you’re trying to mix block with mods to the same block with the same mods.
ctx: {"block":"mix-mod","mods":{"m":1},"mix":[{"mods":{"m":2}}]}
mixes from templates: [{"mods":{"m":2}}]

BEM-XJST WARNING: you’re trying to mix block with mods to the same block with the same mods.
ctx: {"block":"mix-mod","mix":[{"mods":{"type":"test"}},{"mods":{"type":"shmest"}}]}

BEM-XJST WARNING: you’re trying to mix block with mods to the same block with the same mods.
ctx: {"block":"mix-mod","mix":[{"mods":{"type":"test"}},{"mods":{"type":"shmest"}}]}
mixes from templates: [{"mods":{"type":"test"}},{"mods":{"type":"shmest"}}]

BEM-XJST WARNING: you’re trying to mix block with mods to the same block with the same mods.
ctx: {"block":"mix-mod-tmpl","mods":{"color":"red"}}
mixes from templates: [null,{"mods":{"color":"green"}}]
```

**Comment by miripiruni** [comment]
Updated.

**Comment by miripiruni** [comment]
Moreover:

```bash

BEM-XJST WARNING: wrong block name.
Block name can not contain modifier delimeter nor elem delimeter.
block: bad__name
ctx: {"block":"bad__name"}

BEM-XJST WARNING: wrong block name.
Block name can not contain modifier delimeter nor elem delimeter.
block: bad_name
ctx: {"block":"bad_name"}

BEM-XJST WARNING: wrong elem name.
Element name can not contain modifier delimeter nor elem delimeter.
elem: e_e
ctx: {"block":"b","elem":"e_e"}

BEM-XJST WARNING: wrong elem name.
Element name can not contain modifier delimeter nor elem delimeter.
elem: e__e
ctx: {"block":"b","elem":"e__e"}

BEM-XJST WARNING: wrong modifier name.
Modifier name can not contain modifier delimeter nor elem delimeter.
mods: {"mod_name":"bad"}
ctx: {"block":"b","mods":{"mod_name":"bad"}}

BEM-XJST WARNING: wrong modifier name.
Modifier name can not contain modifier delimeter nor elem delimeter.
mods: {"mod__name":"bad"}
ctx: {"block":"b","mods":{"mod__name":"bad"}}

BEM-XJST WARNING: wrong modifier value.
Modifier value can not contain modifier delimeter nor elem delimeter.
mods: {"modName":"very_bad"}
ctx: {"block":"b","mods":{"modName":"very_bad"}}

BEM-XJST WARNING: wrong modifier value.
Modifier value can not contain modifier delimeter nor elem delimeter.
mods: {"modName":"very__bad"}
ctx: {"block":"b","mods":{"modName":"very__bad"}}

BEM-XJST WARNING: wrong element modifier name.
Modifier name can not contain modifier delimeter nor elem delimeter.
elemMods: {"mod_name":"bad"}
ctx: {"block":"b","elem":"e","elemMods":{"mod_name":"bad"}}

BEM-XJST WARNING: wrong element modifier name.
Modifier name can not contain modifier delimeter nor elem delimeter.
elemMods: {"mod__name":"bad"}
ctx: {"block":"b","elem":"e","elemMods":{"mod__name":"bad"}}

BEM-XJST WARNING: wrong element modifier value.
Modifier value can not contain modifier delimeter nor elem delimeter.
elemMods: {"modName":"very_bad"}
ctx: {"block":"b","elem":"e","elemMods":{"modName":"very_bad"}}

BEM-XJST WARNING: wrong element modifier value.
Modifier value can not contain modifier delimeter nor elem delimeter.
elemMods: {"modName":"very__bad"}
ctx: {"block":"b","elem":"e","elemMods":{"modName":"very__bad"}}
```

**Comment by awinogradov** [comment]
👍 🔥

**Pull request merged**
